#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="bridge_discord"
source /assets/defaults/matrix_bridges
source /assets/defaults/bridge_discord

check_container_initialized
#check_service_initialized 10-matrix_bridges
liftoff

print_start "Starting Discord bridge version ${DISCORD_VERSION}"
sudo -u matrix exec /usr/bin/mautrix-discord \
                                                -c "${WHATSAPP_CONFIG_PATH}"/"${WHATSAPP_CONFIG_FILE}"