#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="bridge_neta"
source /assets/defaults/matrix_bridges
source /assets/defaults/bridge_meta

check_container_initialized
#check_service_initialized 10-matrix_bridges-init
liftoff
cd "${LOG_PATH}"print_start "Starting Meta bridge version ${META_VERSION}"
cd /home/matrix
sudo -u matrix exec /usr/bin/mautrix-meta \
                                          -c "${META_CONFIG_PATH}"/"${META_CONFIG_FILE}"
