#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="bridge_whatsapp"
source /assets/defaults/matrix_bridges
source /assets/defaults/bridge_whatsapp

check_container_initialized
check_service_initialized 10-matrix_bridges

liftoff

print_start "Starting Whatsapp bridge version ${WHATSAPP_VERSION}"
sudo -u matrix exec /usr/bin/mautrix-whatsapp
