#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="bridge_facebook"
source /assets/defaults/matrix_bridges
source /assets/defaults/bridge_facebook

check_container_initialized
#check_service_initialized 10-matrix_bridges-init
liftoff
cd "${LOG_PATH}"
print_start "Starting Facebook bridge version ${META_VERSION}"
sudo -u matrix /usr/bin/mautrix-meta \
                                    -c "${FACEBOOK_CONFIG_PATH}"/"${FACEBOOK_CONFIG_FILE}"
